apiVersion: v1
kind: Pod
metadata:
  name: github-slack-bot
spec:
  containers:
    - name: github-slack-bot
      image: quay.io/sjohn/github-slack-bot:0.1
      imagePullPolicy: Always
      env:
        - name: SLACK_APP_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: apptoken
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: slack-app
              key: bottoken

        - name: GITHUB_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: github
              key: apikey
        - name: GITHUB_ORG
          valueFrom:
            secretKeyRef:
              name: github
              key: org
        - name: GITHUB_REPO
          valueFrom:
            secretKeyRef:
              name: github
              key: repo
        - name: GITHUB_ENTERPRISE_URL
          valueFrom:
            secretKeyRef:
              name: github
              key: enturl
